#!/usr/bin/env node
// CLI reporting only; live checks are shared with the operator Edge Function.
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { runLiveHealthChecks } from './live.mjs';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const REPORT_DIR = path.join(ROOT, 'health-reports');
const STATUSES = ['HEALTHY', 'NEEDS_ATTENTION', 'RISK', 'NOT_OBSERVABLE', 'PROBE_ERROR'];
const expected = { customer: { package: 'com.nandyalride.customer', project: '1158ff7e-1da5-4a6a-9080-14791394da7a', runtime: 'customer-1.0.3', channel: 'production-customer' }, captain: { package: 'com.nandyalride.captain', project: '6acc15fd-28b0-4f3a-b825-7e8e5d05cc13', runtime: 'captain-1.0.4', channel: 'production-captain' } };
const alert = (trigger, severity, reason, suggestedResponse) => ({ trigger, severity, reason, suggestedResponse });
function readEnv(file) { if (!fs.existsSync(file)) return {}; return Object.fromEntries(fs.readFileSync(file, 'utf8').split(/\r?\n/).flatMap((line) => { const hit = line.match(/^\s*(?:export\s+)?([A-Za-z_][A-Za-z0-9_]*)=(.*)$/); return hit ? [[hit[1], hit[2].trim().replace(/^(?:"|')|(?:"|')$/g, '')]] : []; })); }
const env = { ...readEnv(path.join(ROOT, '.env')), ...readEnv(path.join(ROOT, '.env.local')), ...process.env };
const present = (name) => Boolean(env[name]?.trim());
function parse() { const values = process.argv.slice(2); const window = values[values.indexOf('--window') + 1] || '24h'; const duration = { '15m': 900_000, '1h': 3_600_000, '6h': 21_600_000, '24h': 86_400_000 }[window]; if (!duration) throw new Error('Invalid --window. Use 15m, 1h, 6h, or 24h.'); return { window, duration, criticalOnly: values.includes('--critical-only') }; }
function appConfig(app) { const text = fs.readFileSync(path.join(ROOT, 'apps', app, 'app.config.ts'), 'utf8'); const match = (pattern) => text.match(pattern)?.[1] ?? null; return { package: match(/package: '([^']+)'/), project: match(/const projectId = '([^']+)'/), runtime: match(/runtimeVersion: '([^']+)'/), channel: match(/'expo-channel-name': '([^']+)'/) }; }
function markdown(report) { const lines = ['# SAWAARI PRODUCTION HEALTH AUDIT', '', `Timestamp: ${report.timestamp}`, 'Environment: production (read-only)', `Observation window: ${report.observationWindow}`, '', `## Overall status: ${report.overall}`, '', ...STATUSES.map((s) => `${s.replaceAll('_', ' ')}: ${report.counts[s]}`), '', '| Service | Component | Status | Metric | Current Value | Threshold | Evidence | Reason | Recommended Alert |', '| --- | --- | --- | --- | --- | --- | --- | --- | --- |']; for (const finding of report.findings) lines.push(`| ${finding.service} | ${finding.component} | ${finding.status} | ${finding.metric} | ${finding.value} | ${finding.threshold} | ${finding.evidence} | ${finding.reason} | ${finding.recommendedAlert?.trigger ?? '—'} |`); return lines.join('\n'); }

async function main() {
  const options = parse(); const findings = [];
  const add = (service, component, status, metric, value, threshold, evidence, reason, recommendedAlert = null, cadence = 'DAILY MORNING AUDIT') => findings.push({ service, component, status, metric, value: String(value), threshold, evidence, reason, recommendedAlert, cadence });
  add('System configuration', 'Production Supabase URL', /^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(env.EXPO_PUBLIC_SUPABASE_URL || '') ? 'HEALTHY' : 'RISK', 'URL configuration', present('EXPO_PUBLIC_SUPABASE_URL') ? 'PRESENT' : 'MISSING', 'PRESENT and HTTPS Supabase project URL', 'Local environment name only', present('EXPO_PUBLIC_SUPABASE_URL') ? 'Configuration is present; live service health is separate.' : 'Production public Supabase URL is absent or malformed.', alert('Production Supabase URL missing', 'RISK', 'Mobile apps cannot initialize their backend client.', 'Restore the approved production URL.'));
  add('System configuration', 'Supabase publishable key', present('EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY') ? 'HEALTHY' : 'RISK', 'Publishable key', present('EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY') ? 'PRESENT' : 'MISSING', 'PRESENT', 'Local environment name only', present('EXPO_PUBLIC_SUPABASE_PUBLISHABLE_KEY') ? 'Configuration is present.' : 'Required public credential is absent.', alert('Supabase publishable key missing', 'RISK', 'Production clients cannot authenticate to the API.', 'Restore the public/publishable key.'));
  const found = { customer: appConfig('customer'), captain: appConfig('captain') };
  for (const app of ['customer', 'captain']) { const mismatch = Object.keys(expected[app]).filter((key) => found[app][key] !== expected[app][key]); add(`${app === 'customer' ? 'Customer' : 'Captain'} app`, 'Static production identity', mismatch.length ? 'RISK' : 'HEALTHY', 'Package / EAS project / runtime / channel', mismatch.length ? `MISMATCHED: ${mismatch.join(', ')}` : 'MATCHED', 'Expected isolated identity', `apps/${app}/app.config.ts`, mismatch.length ? 'Static release identity diverges from its release guard.' : 'Static identity matches its release guard.', alert(`${app} OTA identity mismatch`, 'RISK', 'A mis-targeted update can deliver the wrong app experience or storage namespace.', 'Pause releases; inspect compiled manifests and EAS metadata.'), 'REAL-TIME / HIGH PRIORITY'); add(`${app === 'customer' ? 'Customer' : 'Captain'} app`, 'Remote OTA / latest release', 'NOT_OBSERVABLE', 'Latest update group and release timestamp', 'unavailable', 'EAS Update API read access', 'EAS Update API', 'Static config cannot prove deployed targeting.'); }
  const collision = Object.keys(expected.customer).some((key) => found.customer[key] === found.captain[key]); add('Release isolation', 'Customer/Captain namespace collision', collision ? 'RISK' : 'HEALTHY', 'Static package/project/runtime/channel collision', collision ? 'COLLISION DETECTED' : 'NONE', 'No shared identity namespace', 'Checked-in app config', collision ? 'At least one release identity overlaps.' : 'Static Customer and Captain identities are distinct.', alert('Customer/Captain OTA identity collision', 'RISK', 'Cross-app update delivery is a serious release and data-isolation risk.', 'Stop OTA releases; verify compiled manifests and EAS metadata.'), 'REAL-TIME / HIGH PRIORITY');
  await runLiveHealthChecks({ add, env, windowMs: options.duration });
  for (const [service, component, reason] of [['Authentication', 'OTP/Twilio delivery', 'No provider metrics API/read credential is configured; this audit never sends SMS.'], ['Customer app', 'Crash and non-fatal error health', 'Crashlytics is wired, but no aggregate metrics API is configured.'], ['Captain app', 'Crash and non-fatal error health', 'Crashlytics is wired, but no aggregate metrics API is configured.'], ['Supabase', 'Connections, logs, and Edge Function failures', 'This requires Management API/log-query access.'], ['Push notifications', 'Provider submission and device delivery', 'No safe aggregate receipt/log query is configured.'], ['Google Maps', 'Quota and provider errors', 'No Google Cloud Monitoring read access is configured.'], ['Website', 'Public/legal endpoint availability', 'No canonical production URLs are configured.'], ['KYC/documents', 'Captain eligibility versus document state', 'No aggregate operator monitoring query is configured.'], ['Account deletion / anti-abuse', 'Deletion integrity', 'No aggregate deletion audit event/query is configured.'], ['Storage', 'Bucket and orphaned-reference health', 'Storage telemetry is not configured; documents are never downloaded.']]) add(service, component, 'NOT_OBSERVABLE', 'Provider telemetry', 'unavailable', 'Provider/API integration', 'Monitoring configuration', reason);
  const counts = Object.fromEntries(STATUSES.map((status) => [status, findings.filter((f) => f.status === status).length])); const overall = counts.RISK ? 'RISK' : counts.NEEDS_ATTENTION ? 'NEEDS_ATTENTION' : counts.NOT_OBSERVABLE || counts.PROBE_ERROR ? 'NOT_OBSERVABLE' : 'HEALTHY'; const report = { title: 'SAWAARI PRODUCTION HEALTH AUDIT', timestamp: new Date().toISOString(), environment: 'production', readOnly: true, observationWindow: options.window, overall, counts, findings };
  fs.mkdirSync(REPORT_DIR, { recursive: true }); const base = path.join(REPORT_DIR, `health-audit-${report.timestamp.replace(/[:.]/g, '-')}`); fs.writeFileSync(`${base}.json`, `${JSON.stringify(report, null, 2)}\n`, { mode: 0o600 }); fs.writeFileSync(`${base}.md`, `${markdown(report)}\n`, { mode: 0o600 }); console.log(markdown(options.criticalOnly ? { ...report, findings: findings.filter((f) => f.status === 'RISK') } : report)); console.log(`\nReports: ${base}.md and ${base}.json`); process.exitCode = counts.RISK ? 1 : 0;
}
main().catch((error) => { console.error(`Health audit could not execute reliably: ${error instanceof Error ? error.message : 'unknown error'}`); process.exitCode = 2; });
