import * as Location from 'expo-location';
import MapView from 'react-native-maps';
import React, { useEffect, useRef, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTranslation } from 'react-i18next';
import { LiveLocationMap, type LiveCoordinate } from '../../components/LiveLocationMap';
import { mockRideRequestService } from '../../services/mockRideRequestService';
import type { MockRideRequest } from '../../services/mockRideRequestService';
import { IncomingRideRequestSheet } from './IncomingRideRequestSheet';
import { colors, fontFamily, fontSize, radii, shadows } from '../../theme';
export function CaptainDashboardScreen({ online, onToggle, onSettings, onRequest, request, onAccept, onReject, requestCycle }: { online: boolean; onToggle: () => void; onSettings: () => void; onRequest: (request: MockRideRequest) => void; request: MockRideRequest | null; onAccept: () => void; onReject: () => void; requestCycle: number }) {
  const { t } = useTranslation(); const mapRef = useRef<MapView>(null); const [location, setLocation] = useState<LiveCoordinate | null>(null); const [locationUnavailable, setLocationUnavailable] = useState(false);
  useEffect(() => { let active = true; let subscription: Location.LocationSubscription | null = null; const start = async () => { const permission = await Location.requestForegroundPermissionsAsync(); if (!active || permission.status !== 'granted') { setLocationUnavailable(true); return; } try { const current = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced }); if (!active) return; const coordinate = { latitude: current.coords.latitude, longitude: current.coords.longitude }; setLocation(coordinate); mapRef.current?.animateToRegion({ ...coordinate, latitudeDelta: 0.018, longitudeDelta: 0.018 }, 500); subscription = await Location.watchPositionAsync({ accuracy: Location.Accuracy.Balanced, distanceInterval: 10 }, (next) => setLocation({ latitude: next.coords.latitude, longitude: next.coords.longitude })); } catch { if (active) setLocationUnavailable(true); } }; void start(); return () => { active = false; subscription?.remove(); }; }, []);
  useEffect(() => { if (!online || request) return; return mockRideRequestService.subscribe(onRequest); }, [online, onRequest, request, requestCycle]);
  return <SafeAreaView style={styles.safe} edges={['top', 'left', 'right']}><LiveLocationMap mapRef={mapRef} location={location} /><View style={styles.header}><View style={[styles.badge, online ? styles.onlineBadge : styles.offlineBadge]}><Text style={styles.badgeText}>{online ? t('captain.onlineWaiting') : t('captain.offlineStatus')}</Text></View><Pressable onPress={onSettings} accessibilityRole="button" accessibilityLabel={t('actions.settings')} style={[styles.settings, shadows.card]}><Text style={styles.settingsIcon}>⚙</Text></Pressable></View>{locationUnavailable && <View style={[styles.locationNotice, shadows.card]}><Text style={styles.locationText}>{t('home.locationUnavailable')}</Text></View>}{request ? <IncomingRideRequestSheet request={request} onAccept={onAccept} onReject={onReject} /> : <View style={[styles.bottom, shadows.card]}><Text style={styles.bottomTitle}>{t(online ? 'captain.online' : 'captain.offline')}</Text><Text style={styles.bottomDetail}>{t(online ? 'captain.onlineWaiting' : 'captain.offlineDetail')}</Text><Pressable accessibilityRole="switch" accessibilityState={{ checked: online }} onPress={onToggle} style={[styles.toggle, online ? styles.toggleOnline : styles.toggleOffline]}><View style={[styles.knob, online && styles.knobOnline]} /><Text style={styles.toggleText}>{t(online ? 'captain.goOffline' : 'captain.goOnline')}</Text></Pressable></View>}</SafeAreaView>;
}
const styles = StyleSheet.create({ safe: { backgroundColor: colors.bg, flex: 1 }, header: { flexDirection: 'row', justifyContent: 'space-between', padding: 16 }, badge: { borderRadius: radii.pill, paddingHorizontal: 14, paddingVertical: 10 }, onlineBadge: { backgroundColor: colors.success }, offlineBadge: { backgroundColor: '#6B7280' }, badgeText: { color: colors.textOnPrimary, fontFamily, fontSize: fontSize.sm, fontWeight: '800' }, settings: { alignItems: 'center', backgroundColor: colors.surface, borderRadius: radii.pill, height: 42, justifyContent: 'center', width: 42 }, settingsIcon: { color: colors.primary, fontSize: 22 }, locationNotice: { alignSelf: 'center', backgroundColor: colors.surface, borderRadius: radii.pill, marginTop: 6, paddingHorizontal: 16, paddingVertical: 10 }, locationText: { color: colors.textSecondary, fontFamily, fontSize: fontSize.sm }, bottom: { backgroundColor: colors.surface, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, bottom: 0, gap: 8, left: 0, padding: 22, position: 'absolute', right: 0 }, bottomTitle: { color: colors.textPrimary, fontFamily, fontSize: fontSize.xl, fontWeight: '900' }, bottomDetail: { color: colors.textSecondary, fontFamily, fontSize: fontSize.sm }, toggle: { alignItems: 'center', borderRadius: radii.pill, flexDirection: 'row', gap: 10, justifyContent: 'center', marginTop: 7, minHeight: 58, paddingHorizontal: 18 }, toggleOnline: { backgroundColor: colors.primary }, toggleOffline: { backgroundColor: '#6B7280' }, knob: { backgroundColor: '#FFFFFF', borderRadius: 11, height: 22, width: 22 }, knobOnline: { backgroundColor: colors.surfaceMint }, toggleText: { color: colors.textOnPrimary, fontFamily, fontSize: fontSize.md, fontWeight: '900' } });
