import React, { useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import type { CaptainRideRequest } from '../../services/rideDispatch';
import { formatFare, formatNumber } from '../../utils/format';
import { colors, fontFamily, fontSize, radii, shadows } from '../../theme';
export function IncomingRideRequestSheet({ request, onAccept, onReject, bottomOffset = 0 }: { request: CaptainRideRequest; onAccept: () => Promise<void>; onReject: () => void; bottomOffset?: number }) { const { t } = useTranslation(); const [seconds, setSeconds] = useState(() => Math.max(0, Math.ceil((new Date(request.expiresAt).getTime() - Date.now()) / 1000))); const [accepting, setAccepting] = useState(false); useEffect(() => { setSeconds(Math.max(0, Math.ceil((new Date(request.expiresAt).getTime() - Date.now()) / 1000))); setAccepting(false); }, [request.expiresAt]); useEffect(() => { if (seconds === 0) { onReject(); return; } const timer = setTimeout(() => setSeconds((value) => value - 1), 1000); return () => clearTimeout(timer); }, [seconds, onReject]); const accept = async () => { if (accepting) return; setAccepting(true); try { await onAccept(); } finally { setAccepting(false); } }; return <View style={[styles.sheet, { bottom: bottomOffset }, shadows.card]}><View style={styles.handle} /><View style={styles.heading}><View style={styles.headingContent}><Text style={styles.title}>{t('captain.requestTitle')}</Text><Text style={styles.pickup}>{request.pickupArea}</Text></View><View style={styles.timer}><Text style={styles.timerNumber}>{formatNumber(seconds)}</Text><Text style={styles.timerLabel}>{t('captain.seconds')}</Text></View></View><View style={styles.details}><Detail icon="⌖" label={t('captain.pickupEta')} value={`${formatNumber(request.distanceKm)} km · ${formatNumber(request.etaMinutes)} min`} /><Detail icon="₹" label={t('captain.fare')} value={formatFare(request.fare)} /></View><View style={styles.actions}><Pressable disabled={accepting} onPress={onReject} style={[styles.reject, accepting && styles.disabled]}><Text style={styles.rejectText}>{t('captain.rejectRide')}</Text></Pressable><Pressable disabled={accepting} onPress={() => { void accept(); }} style={[styles.accept, accepting && styles.disabled]}><Text style={styles.acceptText}>{t('captain.accept')}</Text></Pressable></View></View>; }
function Detail({ icon, label, value }: { icon: string; label: string; value: string }) { return <View style={styles.detail}><Text style={styles.detailIcon}>{icon}</Text><View><Text style={styles.detailLabel}>{label}</Text><Text style={styles.detailValue}>{value}</Text></View></View>; }
const styles = StyleSheet.create({ sheet: { backgroundColor: colors.surface, borderTopLeftRadius: radii.xl, borderTopRightRadius: radii.xl, bottom: 0, gap: 16, left: 0, padding: 20, position: 'absolute', right: 0 }, handle: { alignSelf: 'center', backgroundColor: colors.border, borderRadius: 3, height: 5, width: 42 }, heading: { alignItems: 'flex-start', flexDirection: 'row', gap: 12 }, headingContent: { flex: 1, minWidth: 0 }, title: { color: colors.textPrimary, fontFamily, fontSize: fontSize.xl, fontWeight: '900' }, pickup: { color: colors.textSecondary, fontFamily, fontSize: fontSize.sm, marginTop: 3 }, timer: { alignItems: 'center', backgroundColor: colors.accentLight, borderRadius: radii.md, flexShrink: 0, minWidth: 58, padding: 7 }, timerNumber: { color: colors.accent, fontFamily, fontSize: fontSize.xl, fontWeight: '900' }, timerLabel: { color: colors.accent, fontFamily, fontSize: fontSize.xs, fontWeight: '800' }, details: { flexDirection: 'row', gap: 10 }, detail: { alignItems: 'center', backgroundColor: colors.bg, borderRadius: radii.md, flex: 1, flexDirection: 'row', gap: 8, padding: 11 }, detailIcon: { color: colors.primary, fontSize: 19, fontWeight: '900' }, detailLabel: { color: colors.textMuted, fontFamily, fontSize: fontSize.xs }, detailValue: { color: colors.textPrimary, fontFamily, fontSize: fontSize.sm, fontWeight: '800' }, actions: { flexDirection: 'row', gap: 10 }, reject: { alignItems: 'center', backgroundColor: colors.errorLight, borderRadius: radii.pill, flex: 1, justifyContent: 'center', minHeight: 54 }, rejectText: { color: colors.error, fontFamily, fontSize: fontSize.md, fontWeight: '900' }, accept: { alignItems: 'center', backgroundColor: colors.primary, borderRadius: radii.pill, flex: 1, justifyContent: 'center', minHeight: 54 }, acceptText: { color: colors.textOnPrimary, fontFamily, fontSize: fontSize.md, fontWeight: '900' }, disabled: { opacity: 0.6 } });
