import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { PrimaryButton } from '../../components/PrimaryButton';
import { ScreenShell } from '../../components/ScreenShell';
import { mockTripService } from '../../services/mockTripService';
import { colors, fontFamily, fontSize, radii, shadows } from '../../theme';
export function RateCustomerScreen({ onDone }: { onDone: () => void }) { const { t } = useTranslation(); const [stars, setStars] = useState(0); const [note, setNote] = useState(''); const [saving, setSaving] = useState(false); const finish = async (skip = false) => { setSaving(true); if (!skip) await mockTripService.saveCustomerRating({ stars, note: note.trim() }); setSaving(false); onDone(); }; return <ScreenShell title={t('captain.rateCustomerTitle')}><View style={styles.hero}><Text style={styles.emoji}>⭐</Text><Text style={styles.title}>{t('captain.rateCustomerTitle')}</Text><Text style={styles.subtitle}>{t('captain.rateCustomerSubtitle')}</Text></View><View style={[styles.card, shadows.soft]}><View style={styles.stars}>{[1, 2, 3, 4, 5].map((star) => <Pressable key={star} onPress={() => setStars(star)} hitSlop={8}><Text style={[styles.star, star <= stars && styles.starActive]}>★</Text></Pressable>)}</View><TextInput value={note} onChangeText={setNote} placeholder={t('captain.ratingNotePlaceholder')} placeholderTextColor={colors.textMuted} multiline maxLength={140} style={styles.note} /></View><PrimaryButton label={saving ? t('login.pleaseWait') : t('captain.submitRating')} onPress={() => { void finish(); }} disabled={saving} /><Pressable onPress={() => { void finish(true); }} disabled={saving} style={styles.skip}><Text style={styles.skipText}>{t('captain.skipRating')}</Text></Pressable></ScreenShell>; }
const styles = StyleSheet.create({ hero: { alignItems: 'center', gap: 7, paddingTop: 8 }, emoji: { fontSize: 48 }, title: { color: colors.textPrimary, fontFamily, fontSize: fontSize.xl, fontWeight: '900' }, subtitle: { color: colors.textSecondary, fontFamily, fontSize: fontSize.md, textAlign: 'center' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: 16, padding: 20 }, stars: { flexDirection: 'row', justifyContent: 'center', gap: 8 }, star: { color: colors.border, fontSize: 42 }, starActive: { color: '#F59E0B' }, note: { borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.textPrimary, fontFamily, fontSize: fontSize.md, minHeight: 92, padding: 13, textAlignVertical: 'top' }, skip: { alignItems: 'center', padding: 8 }, skipText: { color: colors.primary, fontFamily, fontSize: fontSize.md, fontWeight: '800' } });
