import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { PrimaryButton } from '../../../components/PrimaryButton';
import { ScreenShell } from '../../../components/ScreenShell';
import type { CaptainPayout } from '../../../services/captainOnboarding';
import { captainOnboardingService } from '../../../services/captainOnboarding';
import { colors, fontFamily, fontSize, radii, shadows } from '../../../theme';
export function PayoutDetailsScreen({ onBack, onFinish }: { onBack: () => void; onFinish: () => Promise<void> }) {
  const { t } = useTranslation(); const [payout, setPayout] = useState<CaptainPayout>({ method: 'bank' }); const [error, setError] = useState(''); const [saving, setSaving] = useState(false);
  const update = (next: Partial<CaptainPayout>) => { setPayout((value) => ({ ...value, ...next })); setError(''); };
  const finish = async () => { const valid = payout.method === 'bank' ? Boolean(payout.accountNumber?.trim() && payout.ifsc?.trim() && payout.accountHolder?.trim()) : Boolean(payout.upiId?.trim().includes('@')); if (!valid) return setError(t('captain.payoutRequired')); setSaving(true); try { await captainOnboardingService.savePayout(payout); await onFinish(); } finally { setSaving(false); } };
  const field = (label: string, key: 'accountNumber' | 'ifsc' | 'accountHolder' | 'upiId', placeholder: string, keyboardType?: 'number-pad') => <View style={styles.field}><Text style={styles.label}>{label}</Text><TextInput value={payout[key] ?? ''} onChangeText={(value) => update({ [key]: value })} placeholder={placeholder} placeholderTextColor={colors.textMuted} style={styles.input} autoCapitalize={key === 'ifsc' ? 'characters' : 'none'} keyboardType={keyboardType} /></View>;
  return <ScreenShell back={onBack} title={t('captain.payoutTitle')}><View style={styles.hero}><Text style={styles.emoji}>💰</Text><Text style={styles.help}>{t('captain.payoutSubtitle')}</Text></View><View style={[styles.card, shadows.soft]}><Text style={styles.label}>{t('captain.payoutMethod')}</Text><View style={styles.methods}>{(['bank', 'upi'] as const).map((method) => <Pressable key={method} onPress={() => update({ method })} style={[styles.method, payout.method === method && styles.active]}><Text style={[styles.methodText, payout.method === method && styles.activeText]}>{method === 'bank' ? t('captain.bankAccount') : t('captain.upiId')}</Text></Pressable>)}</View>{payout.method === 'bank' ? <>{field(t('captain.accountNumber'), 'accountNumber', '1234567890', 'number-pad')}{field(t('captain.ifscCode'), 'ifsc', 'SBIN0001234')}{field(t('captain.accountHolderName'), 'accountHolder', t('captain.fullNamePlaceholder'))}</> : field(t('captain.upiId'), 'upiId', 'name@bank')}</View>{!!error && <Text style={styles.error}>{error}</Text>}<PrimaryButton label={saving ? t('login.pleaseWait') : t('captain.finishSetup')} onPress={() => { void finish(); }} disabled={saving} /></ScreenShell>;
}
const styles = StyleSheet.create({ hero: { alignItems: 'center', gap: 7 }, emoji: { fontSize: 45 }, help: { color: colors.textSecondary, fontFamily, fontSize: fontSize.md, textAlign: 'center' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: 14, padding: 18 }, label: { color: colors.textPrimary, fontFamily, fontSize: fontSize.sm, fontWeight: '800' }, methods: { flexDirection: 'row', gap: 8 }, method: { alignItems: 'center', borderColor: colors.border, borderRadius: radii.pill, borderWidth: 1, flex: 1, minHeight: 46, justifyContent: 'center', paddingHorizontal: 8 }, active: { backgroundColor: colors.primary, borderColor: colors.primary }, methodText: { color: colors.textPrimary, fontFamily, fontSize: fontSize.sm, fontWeight: '800' }, activeText: { color: colors.textOnPrimary }, field: { gap: 7 }, input: { borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.textPrimary, fontFamily, fontSize: fontSize.md, padding: 13 }, error: { color: colors.error, fontFamily, fontSize: fontSize.sm, fontWeight: '700', textAlign: 'center' } });
