import React, { useState } from 'react';
import { Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { SafeAreaView } from 'react-native-safe-area-context';
import { useTranslation } from 'react-i18next';
import { PrimaryButton } from '../components/PrimaryButton';
import { rideDispatchService } from '../services/rideDispatch';
import { formatFare } from '../utils/format';
import { colors, fontFamily, fontSize, radii, shadows } from '../theme';

export function CustomerRideSettlement({ rideId, fare, captainName, paymentStatus, onHome }: { rideId: string; fare: number; captainName: string; paymentStatus: 'pending' | 'declared'; onHome: () => void }) {
  const { t } = useTranslation(); const [method, setMethod] = useState<'cash' | 'upi' | null>(null); const [declared, setDeclared] = useState(paymentStatus === 'declared'); const [saving, setSaving] = useState(false); const [rating, setRating] = useState(0); const [note, setNote] = useState(''); const [error, setError] = useState('');
  const pay = async () => { if (!method) return setError(t('rides.paymentMethodRequired')); setSaving(true); try { await rideDispatchService.confirmCustomerPayment(rideId, method); setDeclared(true); } catch { setError(t('login.tryAgain')); } finally { setSaving(false); } };
  const submitRating = async (skip = false) => { if (!skip && !rating) return setError(t('rides.ratingRequired')); setSaving(true); try { if (!skip) await rideDispatchService.rateCaptain(rideId, rating, note); onHome(); } catch { setError(t('login.tryAgain')); } finally { setSaving(false); } };
  return <SafeAreaView style={settlement.safe}><View style={[settlement.card, shadows.card]}>{!declared ? <><Text style={settlement.emoji}>🏁</Text><Text style={settlement.title}>{t('rides.summaryTitle')}</Text><Text style={settlement.subtitle}>{t('rides.summaryWithCaptain', { captain: captainName })}</Text><View style={settlement.fare}><Text style={settlement.fareLabel}>{t('rides.totalDue')}</Text><Text style={settlement.fareValue}>{formatFare(fare)}</Text></View><Text style={settlement.sectionTitle}>{t('rides.paymentTitle')}</Text><Text style={settlement.helper}>{t('rides.paymentDeclarationHint')}</Text><View style={settlement.methods}>{(['upi', 'cash'] as const).map((value) => <Pressable key={value} onPress={() => { setMethod(value); setError(''); }} style={[settlement.method, method === value && settlement.methodSelected]}><Text style={settlement.methodText}>{value === 'upi' ? 'UPI' : t('rides.cash')}</Text></Pressable>)}</View>{!!error && <Text style={settlement.error}>{error}</Text>}<PrimaryButton label={saving ? t('login.pleaseWait') : t('rides.declarePaymentMethod')} onPress={() => { void pay(); }} disabled={saving} /></> : <><Text style={settlement.emoji}>⭐</Text><Text style={settlement.title}>{t('rides.rateCaptainTitle')}</Text><Text style={settlement.subtitle}>{t('rides.paymentDeclared')}</Text><Text style={settlement.subtitle}>{t('rides.rateCaptainSubtitle', { captain: captainName })}</Text><View style={settlement.stars}>{[1,2,3,4,5].map((star) => <Pressable key={star} onPress={() => { setRating(star); setError(''); }}><Text style={[settlement.star, star <= rating && settlement.starActive]}>★</Text></Pressable>)}</View><TextInput value={note} onChangeText={setNote} placeholder={t('rides.ratingNotePlaceholder')} placeholderTextColor={colors.textMuted} multiline maxLength={280} style={settlement.note} />{!!error && <Text style={settlement.error}>{error}</Text>}<PrimaryButton label={saving ? t('login.pleaseWait') : t('rides.submitRating')} onPress={() => { void submitRating(); }} disabled={saving} /><Pressable onPress={() => { void submitRating(true); }} style={settlement.skip}><Text style={settlement.skipText}>{t('rides.skipRating')}</Text></Pressable></>}</View></SafeAreaView>;
}
const settlement = StyleSheet.create({ safe: { backgroundColor: colors.primaryLight, flex: 1, justifyContent: 'center', padding: 20 }, card: { backgroundColor: colors.surface, borderRadius: radii.xl, gap: 15, padding: 22 }, emoji: { fontSize: 48, textAlign: 'center' }, title: { color: colors.textPrimary, fontFamily, fontSize: fontSize.xl, fontWeight: '900', textAlign: 'center' }, subtitle: { color: colors.textSecondary, fontFamily, fontSize: fontSize.md, textAlign: 'center' }, helper: { color: colors.textMuted, fontFamily, fontSize: fontSize.sm, textAlign: 'center' }, fare: { alignItems: 'center', backgroundColor: colors.primaryLight, borderRadius: radii.lg, gap: 4, padding: 16 }, fareLabel: { color: colors.textSecondary, fontFamily, fontSize: fontSize.sm }, fareValue: { color: colors.primary, fontFamily, fontSize: 30, fontWeight: '900' }, sectionTitle: { color: colors.textPrimary, fontFamily, fontSize: fontSize.md, fontWeight: '900' }, methods: { flexDirection: 'row', gap: 10 }, method: { alignItems: 'center', borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, flex: 1, padding: 15 }, methodSelected: { backgroundColor: colors.primaryLight, borderColor: colors.primary, borderWidth: 2 }, methodText: { color: colors.textPrimary, fontFamily, fontSize: fontSize.md, fontWeight: '900' }, stars: { flexDirection: 'row', justifyContent: 'center' }, star: { color: colors.border, fontSize: 42 }, starActive: { color: '#F59E0B' }, note: { borderColor: colors.border, borderRadius: radii.md, borderWidth: 1, color: colors.textPrimary, fontFamily, minHeight: 88, padding: 12, textAlignVertical: 'top' }, error: { color: colors.error, fontFamily, fontSize: fontSize.sm, fontWeight: '700', textAlign: 'center' }, skip: { alignItems: 'center', padding: 6 }, skipText: { color: colors.primary, fontFamily, fontSize: fontSize.md, fontWeight: '800' } });
