import React, { useState } from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { NumericCodeInput } from '../../components/NumericCodeInput';
import { PrimaryButton } from '../../components/PrimaryButton';
import { ScreenShell } from '../../components/ScreenShell';
import { colors, fontFamily, fontSize, radii, shadows } from '../../theme';
export function StartRideScreen({ onBack, onVerified }: { onBack: () => void; onVerified: (otp: string) => Promise<void> }) { const { t } = useTranslation(); const [otp, setOtp] = useState(''); const [error, setError] = useState(''); const [checking, setChecking] = useState(false); const otpLength = 6; const submit = async () => { if (otp.length !== otpLength) return setError(t('captain.otpLengthError')); setChecking(true); try { await onVerified(otp); } catch { setError(t('captain.otpMismatch')); } finally { setChecking(false); } }; return <ScreenShell back={onBack} title={t('captain.startRideTitle')}><View style={styles.hero}><Text style={styles.emoji}>🔐</Text><Text style={styles.title}>{t('captain.customerOtpTitle')}</Text><Text style={styles.subtitle}>{t('captain.customerOtpSubtitle')}</Text></View><View style={[styles.card, shadows.soft]}><Text style={styles.label}>{t('captain.customerOtpLabel')}</Text><NumericCodeInput value={otp} length={otpLength} onChangeText={(value) => { setOtp(value); setError(''); }} /></View>{!!error && <Text style={styles.error}>{error}</Text>}<PrimaryButton label={checking ? t('login.pleaseWait') : t('captain.startTrip')} onPress={() => { void submit(); }} disabled={checking} /></ScreenShell>; }
const styles = StyleSheet.create({ hero: { alignItems: 'center', gap: 8, paddingTop: 14 }, emoji: { fontSize: 48 }, title: { color: colors.textPrimary, fontFamily, fontSize: fontSize.xl, fontWeight: '900', textAlign: 'center' }, subtitle: { color: colors.textSecondary, fontFamily, fontSize: fontSize.md, lineHeight: 25, textAlign: 'center' }, card: { backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, gap: 8, padding: 18 }, label: { color: colors.textPrimary, fontFamily, fontSize: fontSize.sm, fontWeight: '800' }, error: { color: colors.error, fontFamily, fontSize: fontSize.sm, fontWeight: '700', textAlign: 'center' } });
