import * as ImagePicker from 'expo-image-picker';
import React, { useCallback, useEffect, useState } from 'react';
import { Pressable, StyleSheet, Text, View } from 'react-native';
import { useTranslation } from 'react-i18next';
import { PrimaryButton } from '../../components/PrimaryButton';
import { ScreenShell } from '../../components/ScreenShell';
import { useDialog } from '../../components/ThemedDialog';
import { captainDocumentsService, type CaptainManagedDocument } from '../../services/captainDocuments';
import { colors, fontFamily, fontSize, radii, shadows } from '../../theme';

const labels = { license: 'captain.drivingLicense', rc: 'captain.vehicleRc', insurance: 'captain.insurance' } as const;
const icon = { license: '🪪', rc: '🚗', insurance: '🛡️' } as const;

export function YourDocumentsScreen({ onBack }: { onBack: () => void }) {
  const { t } = useTranslation(); const dialog = useDialog();
  const [documents, setDocuments] = useState<CaptainManagedDocument[]>([]); const [loading, setLoading] = useState(true); const [busyId, setBusyId] = useState<string | null>(null);
  const load = useCallback(async () => { setLoading(true); try { setDocuments(await captainDocumentsService.list()); } catch { dialog({ title: t('captain.yourDocuments'), message: t('login.tryAgain') }); } finally { setLoading(false); } }, [dialog, t]);
  useEffect(() => { void load(); }, [load]);
  const requestChange = (document: CaptainManagedDocument) => dialog({ title: t('captain.requestDocumentChange'), message: t('captain.requestDocumentChangeHint'), buttons: [{ text: t('actions.cancel'), style: 'cancel' }, { text: t('captain.requestDocumentChange'), onPress: () => { void (async () => { setBusyId(document.id); try { await captainDocumentsService.requestChange(document.id); await load(); } catch { dialog({ title: t('captain.yourDocuments'), message: t('login.tryAgain') }); } finally { setBusyId(null); } })(); } }] });
  const replace = async (document: CaptainManagedDocument) => { const permission = await ImagePicker.requestMediaLibraryPermissionsAsync(); if (!permission.granted) { dialog({ title: t('captain.permissionTitle'), message: t('captain.permissionMessage') }); return; } const result = await ImagePicker.launchImageLibraryAsync({ mediaTypes: ['images'], quality: 0.7 }); const asset = result.assets?.[0]; if (result.canceled || !asset) return; setBusyId(document.id); try { await captainDocumentsService.submitReplacement(document, { uri: asset.uri, name: asset.fileName ?? `${document.document_type}.jpg` }); await load(); } catch { dialog({ title: t('captain.yourDocuments'), message: t('login.tryAgain') }); } finally { setBusyId(null); } };
  const status = (document: CaptainManagedDocument) => document.verification_status === 'reupload_required' ? t('captain.documentReuploadRequired') : document.change_request_status === 'requested' ? t('captain.documentChangeRequested') : document.change_request_status === 'approved' ? t('captain.documentChangeApproved') : document.verification_status === 'verified' ? t('captain.documentVerified') : document.verification_status === 'rejected' ? t('captain.documentRejected') : t('captain.documentPending');
  return <ScreenShell back={onBack} title={t('captain.yourDocuments')}><Text style={styles.help}>{t('captain.yourDocumentsHint')}</Text>{loading ? <Text style={styles.help}>{t('login.pleaseWait')}</Text> : documents.map((document) => <View key={document.id} style={[styles.card, shadows.soft]}><Text style={styles.icon}>{icon[document.document_type]}</Text><View style={styles.details}><Text style={styles.title}>{t(labels[document.document_type])}</Text><Text style={styles.status}>{status(document)}</Text>{document.review_note ? <Text style={styles.note}>{document.review_note}</Text> : null}</View>{document.verification_status === 'verified' && document.change_request_status === 'none' ? <Pressable onPress={() => requestChange(document)} disabled={busyId === document.id}><Text style={styles.action}>{t('captain.requestDocumentChange')}</Text></Pressable> : document.verification_status === 'reupload_required' && document.change_request_status === 'approved' ? <Pressable onPress={() => { void replace(document); }} disabled={busyId === document.id}><Text style={styles.action}>{busyId === document.id ? t('login.pleaseWait') : t('captain.reuploadDocument')}</Text></Pressable> : null}</View>)}{!loading && !documents.length ? <Text style={styles.help}>{t('captain.documentsUnavailable')}</Text> : null}<PrimaryButton label={t('actions.done')} onPress={onBack} /></ScreenShell>;
}
const styles = StyleSheet.create({ help: { color: colors.textSecondary, fontFamily, fontSize: fontSize.md, lineHeight: 22, textAlign: 'center' }, card: { alignItems: 'center', backgroundColor: colors.surface, borderColor: colors.border, borderRadius: radii.lg, borderWidth: 1, flexDirection: 'row', gap: 12, padding: 14 }, icon: { fontSize: 30 }, details: { flex: 1, gap: 3 }, title: { color: colors.textPrimary, fontFamily, fontSize: fontSize.md, fontWeight: '800' }, status: { color: colors.primaryDark, fontFamily, fontSize: fontSize.sm, fontWeight: '700' }, note: { color: colors.textSecondary, fontFamily, fontSize: fontSize.sm }, action: { color: colors.accent, fontFamily, fontSize: fontSize.sm, fontWeight: '800', textAlign: 'right' } });
